# Generated by Django 3.2 on 2021-04-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('dr', 'drama'), ('mv', 'movie'), ('pg', 'programming')], default='dr', max_length=3),
        ),
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.DateTimeField(default='', null=True),
        ),
    ]
