# Generated by Django 3.2.3 on 2021-05-17 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=200, verbose_name='할일제목')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='생성날짜')),
                ('date_deadline', models.DateField(verbose_name='데드라인')),
            ],
        ),
        migrations.CreateModel(
            name='TodoList_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='todo/image/%Y/%m')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.todolist')),
            ],
        ),
        migrations.CreateModel(
            name='TodoList_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, upload_to='todo/files/%Y/%m')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.todolist')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.todolist')),
            ],
        ),
    ]
