# Generated by Django 3.2.3 on 2021-05-17 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='content',
            field=models.TextField(max_length=200, null=True, verbose_name='할일제목'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='생성날짜'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='date_deadline',
            field=models.DateField(null=True, verbose_name='데드라인'),
        ),
    ]
