# Generated by Django 3.2.2 on 2021-05-13 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='todolist',
            new_name='todo',
        ),
    ]
